version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4
    ports: 
     - "27018:27017"

  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
     - "8080:8080"
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/usr/src/mean-starter
     - /usr/src/mean-starter/node_modules
